// <auto-generated />
using System;
using ClaudeForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace ClaudeForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260607101026_AddRefreshTokenRootIdIndex")]
    partial class AddRefreshTokenRootIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.CategoryEntity", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Dimension", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_dimension_value");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.DocPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title,'')), 'A') || setweight(to_tsvector('english', coalesce(content_markdown,'')), 'B')", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_doc_pages_slug");

                    b.ToTable("doc_pages", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrgAuditEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OrgId");

                    b.ToTable("org_audit_log", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_name_normalized");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationInvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_normalized");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_invitations_token");

                    b.HasIndex("OrgId", "EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_invitations_pending_org_email")
                        .HasFilter("status = 'pending'");

                    b.ToTable("organization_invitations", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_members_org_user");

                    b.ToTable("organization_members", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginCategoryEntity", b =>
                {
                    b.Property<Guid>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.HasKey("PluginId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("plugin_categories", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("download_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized");

                    b.Property<Guid?>("OwnerOrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_org_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(name,'') || ' ' || coalesce(description,''))", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("public")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_plugins_name_normalized");

                    b.HasIndex("OwnerOrgId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_plugins_slug");

                    b.HasIndex("Visibility", "OwnerOrgId")
                        .HasDatabaseName("idx_plugins_visibility_org");

                    b.ToTable("plugins", null, t =>
                        {
                            t.HasCheckConstraint("chk_visibility_owner", "visibility = 'public' OR owner_org_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("download_count");

                    b.Property<bool>("IsLatest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_latest");

                    b.Property<string>("PackageFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_format");

                    b.Property<string>("PackageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_key");

                    b.Property<Guid>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<string>("ReadmeText")
                        .HasColumnType("text")
                        .HasColumnName("readme_text");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("release_notes");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<long>("VersionSort")
                        .HasColumnType("bigint")
                        .HasColumnName("version_sort");

                    b.HasKey("Id");

                    b.HasIndex("PluginId")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_versions_single_latest")
                        .HasFilter("is_latest = TRUE");

                    b.HasIndex("PluginId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_versions_plugin_version");

                    b.HasIndex("PluginId", "VersionSort")
                        .HasDatabaseName("idx_plugin_versions_sort");

                    b.ToTable("plugin_versions", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("RootId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_id");

                    b.Property<Guid?>("RotatedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("rotated_to");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RootId")
                        .HasDatabaseName("ix_refresh_tokens_root_id");

                    b.HasIndex("RotatedTo");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("chk_refresh_tokens_token_hash_length", "char_length(trim(token_hash)) = 64");
                        });
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.RevokedJtiEntity", b =>
                {
                    b.Property<string>("Jti")
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("Jti");

                    b.ToTable("revoked_jti", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryAggregateEntity", b =>
                {
                    b.Property<Guid>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateOnly>("WindowStart")
                        .HasColumnType("date")
                        .HasColumnName("window_start");

                    b.Property<long>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("count");

                    b.HasKey("PluginId", "Version", "EventType", "WindowStart");

                    b.ToTable("telemetry_aggregates", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnonClientId")
                        .HasColumnType("char(64)")
                        .HasColumnName("anon_client_id");

                    b.Property<string>("ClientArch")
                        .HasColumnType("text")
                        .HasColumnName("client_arch");

                    b.Property<string>("ClientOs")
                        .HasColumnType("text")
                        .HasColumnName("client_os");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_telemetry_events_ts");

                    b.HasIndex("PluginId")
                        .HasDatabaseName("idx_telemetry_events_plugin");

                    b.ToTable("telemetry_events", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .HasColumnType("text")
                        .HasColumnName("email_normalized");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_normalized");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.UserIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_user_identities_provider_subject");

                    b.ToTable("user_identities", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrgAuditEntryEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", "Organization")
                        .WithMany("AuditLog")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationInvitationEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", "InvitedByUser")
                        .WithMany("SentInvitations")
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", "Organization")
                        .WithMany("Invitations")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationMemberEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginCategoryEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.CategoryEntity", "Category")
                        .WithMany("PluginCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", "Plugin")
                        .WithMany("PluginCategories")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerOrgId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginVersionEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", "Plugin")
                        .WithMany("Versions")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.RefreshTokenEntity", "RotatedToToken")
                        .WithMany()
                        .HasForeignKey("RotatedTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RotatedToToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryAggregateEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", null)
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryEventEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", null)
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.UserIdentityEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.CategoryEntity", b =>
                {
                    b.Navigation("PluginCategories");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("Invitations");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", b =>
                {
                    b.Navigation("PluginCategories");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Memberships");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentInvitations");
                });
#pragma warning restore 612, 618
        }
    }
}
