// <auto-generated />
using System;
using ClaudeForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaudeForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260606182703_AddDocPages")]
    partial class AddDocPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.CategoryEntity", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dimension");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Dimension", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_dimension_value");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.DocPageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title,'')), 'A') || setweight(to_tsvector('english', coalesce(content_markdown,'')), 'B')", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_doc_pages_slug");

                    b.ToTable("doc_pages", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginCategoryEntity", b =>
                {
                    b.Property<Guid>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.HasKey("PluginId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("plugin_categories", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("download_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_normalized");

                    b.Property<string>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(name,'') || ' ' || coalesce(description,''))", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_plugins_name_normalized");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_plugins_slug");

                    b.ToTable("plugins", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("download_count");

                    b.Property<bool>("IsLatest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_latest");

                    b.Property<string>("PackageFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_format");

                    b.Property<string>("PackageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_key");

                    b.Property<Guid>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<string>("ReadmeText")
                        .HasColumnType("text")
                        .HasColumnName("readme_text");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("release_notes");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<long>("VersionSort")
                        .HasColumnType("bigint")
                        .HasColumnName("version_sort");

                    b.HasKey("Id");

                    b.HasIndex("PluginId")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_versions_single_latest")
                        .HasFilter("is_latest = TRUE");

                    b.HasIndex("PluginId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_versions_plugin_version");

                    b.HasIndex("PluginId", "VersionSort")
                        .HasDatabaseName("idx_plugin_versions_sort");

                    b.ToTable("plugin_versions", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryAggregateEntity", b =>
                {
                    b.Property<Guid>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateOnly>("WindowStart")
                        .HasColumnType("date")
                        .HasColumnName("window_start");

                    b.Property<long>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("count");

                    b.HasKey("PluginId", "Version", "EventType", "WindowStart");

                    b.ToTable("telemetry_aggregates", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnonClientId")
                        .HasColumnType("char(64)")
                        .HasColumnName("anon_client_id");

                    b.Property<string>("ClientArch")
                        .HasColumnType("text")
                        .HasColumnName("client_arch");

                    b.Property<string>("ClientOs")
                        .HasColumnType("text")
                        .HasColumnName("client_os");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("PluginId")
                        .HasColumnType("uuid")
                        .HasColumnName("plugin_id");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_telemetry_events_ts");

                    b.HasIndex("PluginId")
                        .HasDatabaseName("idx_telemetry_events_plugin");

                    b.ToTable("telemetry_events", (string)null);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginCategoryEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.CategoryEntity", "Category")
                        .WithMany("PluginCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", "Plugin")
                        .WithMany("PluginCategories")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginVersionEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", "Plugin")
                        .WithMany("Versions")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plugin");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryAggregateEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", null)
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.TelemetryEventEntity", b =>
                {
                    b.HasOne("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", null)
                        .WithMany()
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.CategoryEntity", b =>
                {
                    b.Navigation("PluginCategories");
                });

            modelBuilder.Entity("ClaudeForge.Infrastructure.Persistence.Entities.PluginEntity", b =>
                {
                    b.Navigation("PluginCategories");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
